config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'posts/index'
  
  root 'brands#index'

  resources:posts
  resources:products
  resources:brands
  resources:names

  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products
    mount_uploader :image, ImageUploader
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :product
  has_many :posts
  mount_uploader :image, ImageUploader

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_many :names
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
   def index
       @brands = Brand.all
   end
   
   def show
       @brands = Brand.all
       @brand = Brand.find(params[:id])
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
    def show
        @brands = Brand.all
        @name = Name.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def create
      new_post = Post.new(user_id: current_user.id, name_id: params[:name_id], image: params[:image], content: params[:content])
      if new_post.save
        redirect_back(fallback_location: root_path)
      else
        redirect_to new_post_path
      end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
    end
    
    def show
        @product = Product.find(params[:id])
        @brand = @product.brand
        @brands = Brand.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/index.html.erb
<ul class="collection with-header">
 <li class="collection-header"><h4>전체 브랜드</h4></li>
<% @brands.each do |brand| %>
   <li class="collection-item"><%= link_to brand.title, brand_path(brand) %></li>
<% end %>
</ul>

app/views/brands/show.html.erb
<ul class="collection with-header">
     <li class="collection-header"><h4>전체 브랜드</h4></li>
        <% @brands.each do |brand| %>
        <li class="collection-item"><%= link_to brand.title, brand_path(brand) %></li>
        <% end %>
    <li class="collection-header"><h4><%=@brand.title%> 의 제품들</h4></li>
        <% @brand.products.each do |product| %>
        <li class="collection-item"><%= link_to product.title, product_path(product) %></li>
        <% end %>
    
</ul>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LipsTouch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <div class="container">
          <a href="/" class="brand-logo">LIPSTOUCH</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li><%= link_to 'sign out', destroy_user_session_path, method: 'delete' %></li>
            <% else %>
              <li><a href="/users/sign_in">Sign in</a></li>
              <li><a href="/users/sign_up">Sign up</a></li>
            <% end %>
          </ul>
          <ul class="side-nav" id="mobile-demo">
            <li><a href="/posts">Posts</a></li>
            <% if user_signed_in? %>
              <li><%= link_to 'sign out', destroy_user_session_path, method: 'delete' %></li>
            <% else %>
              <li><a href="/users/sign_in">Sign in</a></li>
              <li><a href="/users/sign_up">Sign up</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/names/show.html.erb
<div container>
    <div class="row">
        <div class="col s4">
            <h5>전체브랜드</h5>
            <ul class="collection">
            <% @brands.each do |brand| %>
                <li class="collection-item"><%= link_to brand.title, brand_path(brand) %></li>
            <% end %>
            </ul>
        </div>
        <div class="col s4">
            <h5><%=@name.product.brand.title%> 의 제품들</h5>
            <ul class="collection">
            <% @name.product.brand.products.each do |product| %>
                <li class="collection-item"><%= link_to product.title, product_path(product) %></li>
            <% end %>
            </ul>
        </div>
        <div class="col s4">
            <h5><%=@name.product.title%> 의 호수</h5>
            <ul class="collection">
            <% @name.product.names.each do |name| %>
                <li class="collection-item"><%= link_to name.title, name_path(name) %></li>
            <% end %>
            </ul>
        </div>
    </div>
    
    <h4><%= @name.product.brand.title %> - <%= @name.product.title %> - <%= @name.title %>의 사진들</h4>
    
    <div class="row">
        <div class="card col s12">
          <div class="card-content">
            <div class="card-title"><i class="material-icons">add</i></div>
            <%= form_tag posts_path, multipart: true do %>
                <%= hidden_field_tag :name_id, @name.id %>
             <!-- file 태그 추가 -->
              <div class="input-field">
                <%= file_field_tag :image %>
              </div>
              <div class="input-field">
                <%= text_area_tag :content %>
              </div>
              </br>
              <div class="input-field">
                <%= button_tag "작성하기", class: "btn" %>
                
              </div>
            <% end %>
          </div>
        </div>
    </div>
    
    
    <div class="row">
        <% @name.posts.reverse.each do |post| %>
            <div class="col s6 m6">
                <div class="card">
                    <div class="card-image">
                        <img src="<%= post.image %>">
                    </div>
                    <div class="card-content">
                        <p><%= post.content %></p>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    
</div>

app/views/products/show.html.erb
<ul class="collection with-header">

<li class="collection-header"><h4>전체 브랜드</h4></li>
<% @brands.each do |brand| %>
   <li class="collection-item"><%= link_to brand.title, brand_path(brand) %></li>
<% end %>

 <li class="collection-header"><h4><%=@brand.title%> 의 제품들</h4></li>
        <% @brand.products.each do |product| %>
        <li class="collection-item"><%= link_to product.title, product_path(product) %></li>
        <% end %>
        
<li class="collection-header"><h4><%=@product.title%> 의 호수</h4></li>
<% @product.names.each do |name| %>
    <li class="collection-header"><%= link_to name.title, name_path(name) %></li>
<% end %>
</ul>